apiVersion: v1
kind: Service
metadata:
  name: api-result-service
spec:
  type: LoadBalancer
  ports:
  - name: "result-service"
    port: 5001
    targetPort: 80
    nodePort: 31001
  selector:
    app: myapp
    type: frontend-result-app
