  
apiVersion: v1
kind: Service
metadata:
  name: api-vote-service
spec:
  type: LoadBalancer
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    app: myapp
    type: fronted-vote-app
